import type {
  Tournament,
  Club,
  Player,
  Match,
  MatchEvent,
  StandingsRow,
  PlayerSanction,
  PlayerCategory,
  RosterPlayer,
  StaffMember,
  TeamCategory,
} from "./types";

export const clubs: Club[] = [
  { id: "c1", name: "Deportivo Union", shortName: "UNI", logoUrl: null, ownerId: "u2", playerCount: 18 },
  { id: "c2", name: "Atletico San Martin", shortName: "ASM", logoUrl: null, ownerId: "u3", playerCount: 16 },
  { id: "c3", name: "Club Social Rivera", shortName: "RIV", logoUrl: null, ownerId: "u4", playerCount: 20 },
  { id: "c4", name: "Juventud del Norte", shortName: "JDN", logoUrl: null, ownerId: "u5", playerCount: 15 },
  { id: "c5", name: "Racing Barrio Sur", shortName: "RBS", logoUrl: null, ownerId: "u6", playerCount: 17 },
  { id: "c6", name: "Independiente FC", shortName: "IND", logoUrl: null, ownerId: "u7", playerCount: 19 },
  { id: "c7", name: "Defensores del Lago", shortName: "DEL", logoUrl: null, ownerId: "u8", playerCount: 14 },
  { id: "c8", name: "Sportivo Central", shortName: "SPC", logoUrl: null, ownerId: "u9", playerCount: 16 },
];

export const tournaments: Tournament[] = [
  {
    id: "t1",
    name: "Copa Amistad",
    format: "liga",
    status: "en_curso",
    sportType: "futbol",
    teamsCount: 10,
    maxTeams: 10,
    startDate: "2026-07-15",
    endDate: "2026-09-30",
    location: "Complejo Deportivo Municipal",
    organizerId: "u1",
    matchesPlayed: 12,
    totalMatches: 28,
    category: "Sub 18",
  },
  {
    id: "t2",
    name: "Torneo Apertura 2026",
    format: "grupos",
    status: "inscripcion",
    sportType: "futbol",
    teamsCount: 4,
    maxTeams: 16,
    minTeams: 8,
    startDate: "2026-10-01",
    endDate: null,
    location: "Canchas El Bosque",
    organizerId: "u1",
    matchesPlayed: 0,
    totalMatches: 0,
  },
  {
    id: "t4",
    name: "Copa Interbarrios",
    format: "eliminacion",
    status: "inscripcion",
    sportType: "futbol",
    teamsCount: 10,
    maxTeams: 10,
    minTeams: 8,
    startDate: "2026-10-15",
    endDate: null,
    location: "Estadio La Ribera",
    organizerId: "u1",
    matchesPlayed: 0,
    totalMatches: 0,
    category: "Sub 12",
  },
  {
    id: "t3",
    name: "Liga Primavera 2025",
    format: "liga",
    status: "finalizado",
    sportType: "futbol",
    teamsCount: 6,
    maxTeams: 6,
    startDate: "2025-09-01",
    endDate: "2025-12-15",
    location: "Complejo Deportivo Municipal",
    organizerId: "u1",
    matchesPlayed: 15,
    totalMatches: 15,
  },
];

export const matches: Match[] = [
  {
    id: "m1",
    tournamentId: "t1",
    homeTeam: clubs[0],
    awayTeam: clubs[1],
    homeScore: 3,
    awayScore: 0,
    status: "finalizado",
    date: "2026-06-30",
    time: "15:00",
    location: "Cancha 1",
    matchday: 1,
    group: "Grupo A",
  },
  {
    id: "m2",
    tournamentId: "t1",
    homeTeam: clubs[2],
    awayTeam: clubs[3],
    homeScore: 2,
    awayScore: 1,
    status: "finalizado",
    date: "2026-06-30",
    time: "17:00",
    location: "Cancha 2",
    matchday: 1,
    group: "Grupo A",
  },
  {
    id: "m3",
    tournamentId: "t1",
    homeTeam: clubs[4],
    awayTeam: clubs[5],
    homeScore: 1,
    awayScore: 1,
    status: "finalizado",
    date: "2026-07-06",
    time: "15:00",
    location: "Cancha 1",
    matchday: 2,
    group: "Grupo A",
  },
  {
    id: "m4",
    tournamentId: "t1",
    homeTeam: clubs[6],
    awayTeam: clubs[7],
    homeScore: 0,
    awayScore: 2,
    status: "finalizado",
    date: "2026-07-06",
    time: "17:00",
    location: "Cancha 2",
    matchday: 2,
    group: "Grupo B",
  },
  {
    id: "m5",
    tournamentId: "t1",
    homeTeam: clubs[0],
    awayTeam: clubs[2],
    homeScore: 2,
    awayScore: 2,
    status: "finalizado",
    date: "2026-07-13",
    time: "15:00",
    location: "Cancha 1",
    matchday: 3,
    group: "Grupo A",
  },
  {
    id: "m6",
    tournamentId: "t1",
    homeTeam: clubs[1],
    awayTeam: clubs[4],
    homeScore: null,
    awayScore: null,
    status: "programado",
    date: "2026-09-07",
    time: "15:00",
    location: "Cancha 1",
    matchday: 4,
    group: "Grupo A",
  },
  {
    id: "m7",
    tournamentId: "t1",
    homeTeam: clubs[3],
    awayTeam: clubs[5],
    homeScore: null,
    awayScore: null,
    status: "programado",
    date: "2026-09-07",
    time: "17:00",
    location: "Cancha 2",
    matchday: 4,
    group: "Grupo B",
  },
  {
    id: "m8",
    tournamentId: "t1",
    homeTeam: clubs[6],
    awayTeam: clubs[0],
    homeScore: null,
    awayScore: null,
    status: "programado",
    date: "2026-09-14",
    time: "15:00",
    location: "Cancha 3",
    matchday: 5,
    group: "Grupo A",
  },
  {
    id: "m9",
    tournamentId: "t4",
    homeTeam: clubs[0],
    awayTeam: clubs[1],
    homeScore: null,
    awayScore: null,
    status: "programado",
    date: "2026-10-17",
    time: "15:00",
    location: "Estadio La Ribera",
    matchday: 1,
    group: "Grupo A",
  },
  {
    id: "m10",
    tournamentId: "t4",
    homeTeam: clubs[2],
    awayTeam: clubs[3],
    homeScore: null,
    awayScore: null,
    status: "programado",
    date: "2026-10-17",
    time: "17:00",
    location: "Estadio La Ribera",
    matchday: 1,
    group: "Grupo A",
  },
  {
    id: "m11",
    tournamentId: "t4",
    homeTeam: clubs[4],
    awayTeam: clubs[5],
    homeScore: null,
    awayScore: null,
    status: "programado",
    date: "2026-10-24",
    time: "15:00",
    location: "Estadio La Ribera",
    matchday: 1,
    group: "Grupo B",
  },
  {
    id: "m12",
    tournamentId: "t4",
    homeTeam: clubs[6],
    awayTeam: clubs[7],
    homeScore: null,
    awayScore: null,
    status: "programado",
    date: "2026-10-24",
    time: "17:00",
    location: "Estadio La Ribera",
    matchday: 1,
    group: "Grupo B",
  },
  {
    id: "m13",
    tournamentId: "t4",
    homeTeam: clubs[0],
    awayTeam: clubs[2],
    homeScore: null,
    awayScore: null,
    status: "programado",
    date: "2026-10-31",
    time: "15:00",
    location: "Estadio La Ribera",
    matchday: 2,
    group: "Grupo A",
  },
  {
    id: "m14",
    tournamentId: "t4",
    homeTeam: clubs[1],
    awayTeam: clubs[3],
    homeScore: null,
    awayScore: null,
    status: "programado",
    date: "2026-10-31",
    time: "17:00",
    location: "Estadio La Ribera",
    matchday: 2,
    group: "Grupo A",
  },
  {
    id: "m15",
    tournamentId: "t4",
    homeTeam: clubs[4],
    awayTeam: clubs[7],
    homeScore: null,
    awayScore: null,
    status: "programado",
    date: "2026-11-07",
    time: "15:00",
    location: "Estadio La Ribera",
    matchday: 2,
    group: "Grupo B",
  },
  {
    id: "m16",
    tournamentId: "t4",
    homeTeam: clubs[5],
    awayTeam: clubs[6],
    homeScore: null,
    awayScore: null,
    status: "programado",
    date: "2026-11-07",
    time: "17:00",
    location: "Estadio La Ribera",
    matchday: 2,
    group: "Grupo B",
  },
];

export const standings: StandingsRow[] = [
  { position: 1, club: clubs[0], played: 5, won: 4, drawn: 1, lost: 0, goalsFor: 12, goalsAgainst: 3, goalDifference: 9, points: 13 },
  { position: 2, club: clubs[2], played: 5, won: 3, drawn: 2, lost: 0, goalsFor: 8, goalsAgainst: 2, goalDifference: 6, points: 11 },
  { position: 3, club: clubs[5], played: 5, won: 3, drawn: 1, lost: 1, goalsFor: 9, goalsAgainst: 5, goalDifference: 4, points: 10 },
  { position: 4, club: clubs[1], played: 5, won: 2, drawn: 2, lost: 1, goalsFor: 7, goalsAgainst: 6, goalDifference: 1, points: 8 },
  { position: 5, club: clubs[4], played: 5, won: 2, drawn: 1, lost: 2, goalsFor: 6, goalsAgainst: 7, goalDifference: -1, points: 7 },
  { position: 6, club: clubs[3], played: 5, won: 1, drawn: 1, lost: 3, goalsFor: 4, goalsAgainst: 8, goalDifference: -4, points: 4 },
  { position: 7, club: clubs[7], played: 5, won: 1, drawn: 0, lost: 4, goalsFor: 3, goalsAgainst: 10, goalDifference: -7, points: 3 },
  { position: 8, club: clubs[6], played: 5, won: 0, drawn: 2, lost: 3, goalsFor: 2, goalsAgainst: 10, goalDifference: -8, points: 2 },
];

export const players: Player[] = [
  { id: "p1", firstName: "Carlos", lastName: "Mendez", number: 9, position: "Delantero", clubId: "c1", goals: 6, assists: 2, yellowCards: 1, redCards: 0, matchesPlayed: 5 },
  { id: "p2", firstName: "Lucas", lastName: "Torres", number: 10, position: "Mediocampista", clubId: "c1", goals: 4, assists: 3, yellowCards: 0, redCards: 0, matchesPlayed: 5 },
  { id: "p3", firstName: "Angel", lastName: "Rodriguez", number: 7, position: "Delantero", clubId: "c1", goals: 5, assists: 1, yellowCards: 2, redCards: 0, matchesPlayed: 5 },
  { id: "p4", firstName: "Diego", lastName: "Fernandez", number: 5, position: "Back central", clubId: "c1", goals: 1, assists: 0, yellowCards: 3, redCards: 1, matchesPlayed: 5 },
  { id: "p5", firstName: "Andres", lastName: "Lopez", number: 1, position: "Arquero", clubId: "c1", goals: 0, assists: 0, yellowCards: 0, redCards: 0, matchesPlayed: 5 },
  { id: "p6", firstName: "Alfonso", lastName: "Franci", number: 3, position: "Back central", clubId: "c1", goals: 0, assists: 1, yellowCards: 1, redCards: 0, matchesPlayed: 4 },
  { id: "p7", firstName: "Mohammed", lastName: "Hassan", number: 8, position: "Mediocampista", clubId: "c1", goals: 2, assists: 2, yellowCards: 0, redCards: 0, matchesPlayed: 5 },
  { id: "p8", firstName: "Jaydon", lastName: "Korsgaard", number: 11, position: "Extremo", clubId: "c1", goals: 1, assists: 3, yellowCards: 0, redCards: 0, matchesPlayed: 4 },
  { id: "p9", firstName: "Andres", lastName: "Espinel", number: 4, position: "Back central", clubId: "c2", goals: 0, assists: 0, yellowCards: 1, redCards: 0, matchesPlayed: 5 },
  { id: "p10", firstName: "Aldo", lastName: "Huapaya", number: 6, position: "Mediocampista", clubId: "c2", goals: 1, assists: 0, yellowCards: 0, redCards: 1, matchesPlayed: 3 },
  { id: "p11", firstName: "Stina", lastName: "Gunnarsdottir", number: 14, position: "Defensor", clubId: "c2", goals: 0, assists: 0, yellowCards: 1, redCards: 1, matchesPlayed: 4 },
  { id: "p12", firstName: "Martin", lastName: "Rodriguez", number: 9, position: "Delantero", clubId: "c2", goals: 3, assists: 1, yellowCards: 0, redCards: 0, matchesPlayed: 5 },
  { id: "p13", firstName: "Andres", lastName: "Espinel", number: 10, position: "Delantero", clubId: "c3", goals: 9, assists: 4, yellowCards: 0, redCards: 0, matchesPlayed: 5 },
  { id: "p14", firstName: "Aldo", lastName: "Shimabukuro", number: 9, position: "Delantero", clubId: "c4", goals: 8, assists: 2, yellowCards: 1, redCards: 0, matchesPlayed: 5 },
  { id: "p15", firstName: "Roberto", lastName: "Campos", number: 7, position: "Extremo", clubId: "c5", goals: 4, assists: 3, yellowCards: 0, redCards: 0, matchesPlayed: 5 },
  { id: "p16", firstName: "Felipe", lastName: "Vargas", number: 11, position: "Delantero", clubId: "c6", goals: 3, assists: 2, yellowCards: 1, redCards: 0, matchesPlayed: 4 },
  { id: "p17", firstName: "Nicolas", lastName: "Paredes", number: 8, position: "Mediocampista", clubId: "c7", goals: 3, assists: 1, yellowCards: 0, redCards: 0, matchesPlayed: 5 },
  { id: "p18", firstName: "Santiago", lastName: "Morales", number: 10, position: "Mediocampista", clubId: "c8", goals: 2, assists: 4, yellowCards: 0, redCards: 0, matchesPlayed: 5 },
];

export const playerSanctions: PlayerSanction[] = [
  { id: "s1", playerName: "Andres Espinel", tournamentId: "t1", clubId: "c2", status: "habilitado", accumulatedCards: 1, cardLimit: 4, hasRedCard: false },
  { id: "s2", playerName: "Aldo Huapaya", tournamentId: "t1", clubId: "c2", status: "suspendido", suspensionFechas: 2, accumulatedCards: 1, cardLimit: 1, hasRedCard: true },
  { id: "s3", playerName: "Diego Fernandez", tournamentId: "t1", clubId: "c1", status: "suspendido", suspensionFechas: 1, accumulatedCards: 3, cardLimit: 4, hasRedCard: true },
  { id: "s4", playerName: "Stina Gunnarsdottir", tournamentId: "t1", clubId: "c2", status: "habilitado", accumulatedCards: 1, cardLimit: 4, hasRedCard: false },
];

export const matchEvents: MatchEvent[] = [
  { id: "e1", matchId: "m1", type: "gol", minute: 15, playerId: "p3", playerName: "Angel Rodriguez", teamId: "c1" },
  { id: "e2", matchId: "m1", type: "gol", minute: 32, playerId: "p3", playerName: "Angel Rodriguez", teamId: "c1" },
  { id: "e3", matchId: "m1", type: "tarjeta_amarilla", minute: 40, playerId: "p11", playerName: "Stina Gunnarsdottir", teamId: "c2" },
  { id: "e4", matchId: "m1", type: "tarjeta_roja", minute: 60, playerId: "p11", playerName: "Stina Gunnarsdottir", teamId: "c2" },
  { id: "e5", matchId: "m1", type: "gol", minute: 70, playerId: "p3", playerName: "Angel Rodriguez", teamId: "c1" },
];

export const playerCategories: PlayerCategory[] = [
  { id: "cat-sub15", name: "Sub 15", gender: "masculino", playerCount: 16 },
  { id: "cat-libre", name: "Libre", gender: "masculino", playerCount: 10 },
  { id: "cat-master", name: "Master", gender: "masculino", playerCount: 20 },
  { id: "cat-sin", name: "Sin categoria", gender: "masculino", playerCount: 12 },
];

export const rosterPlayers: RosterPlayer[] = [
  { id: "rp1", firstName: "Mateo", lastName: "Vargas", position: "Volante", age: 20, avatarUrl: null, verified: true, status: "activo", categoryId: "cat-sub15", clubId: "c1" },
  { id: "rp2", firstName: "Diego", lastName: "Salazar", position: "Volante", age: 20, avatarUrl: null, verified: true, status: "activo", categoryId: "cat-sub15", clubId: "c1" },
  { id: "rp3", firstName: "Renzo", lastName: "Huaman", position: "Volante", age: 20, avatarUrl: null, verified: true, status: "activo", categoryId: "cat-sub15", clubId: "c1" },
  { id: "rp4", firstName: "Sebastian", lastName: "Flores", position: "Volante", age: 20, avatarUrl: null, verified: true, status: "activo", categoryId: "cat-sub15", clubId: "c1" },
  { id: "rp5", firstName: "Joaquin", lastName: "Rios", position: "Volante", age: 20, avatarUrl: null, verified: true, status: "activo", categoryId: "cat-sub15", clubId: "c1" },
  { id: "rp6", firstName: "Fabricio", lastName: "Medina", position: "Volante", age: 20, avatarUrl: null, verified: true, status: "activo", categoryId: "cat-sub15", clubId: "c1" },
  { id: "rp7", firstName: "Luis", lastName: "Rodriguez", position: "Por definir", age: 20, avatarUrl: null, verified: false, status: "en_espera", categoryId: "cat-sub15", clubId: "c1" },
  { id: "rp8", firstName: "Nicolas", lastName: "Paredes", position: "Volante", age: 20, avatarUrl: null, verified: true, status: "activo", categoryId: "cat-sub15", clubId: "c1" },
  { id: "rp9", firstName: "Gonzalo", lastName: "Ramos", position: "Volante", age: 20, avatarUrl: null, verified: true, status: "activo", categoryId: "cat-sub15", clubId: "c1" },
  { id: "rp10", firstName: "Bruno", lastName: "Castillo", position: "Volante", age: 20, avatarUrl: null, verified: true, status: "activo", categoryId: "cat-sub15", clubId: "c1" },
  { id: "rp11", firstName: "Adolfo", lastName: "Cruz", position: "Volante", age: 25, avatarUrl: null, verified: true, status: "activo", categoryId: "cat-sin", clubId: "c1" },
  { id: "rp12", firstName: "Adolfo", lastName: "Cruz", position: "Volante", age: 20, avatarUrl: null, verified: true, status: "activo", categoryId: "cat-sin", clubId: "c1" },
  { id: "rp13", firstName: "Adolfo", lastName: "Cruz", position: "Volante", age: 18, avatarUrl: null, verified: true, status: "activo", categoryId: "cat-sin", clubId: "c1" },
  { id: "rp14", firstName: "Adolfo", lastName: "Cruz", position: "Volante", age: 18, avatarUrl: null, verified: true, status: "activo", categoryId: "cat-sin", clubId: "c1" },
  { id: "rp15", firstName: "Adolfo", lastName: "Cruz", position: "Volante", age: 18, avatarUrl: null, verified: true, status: "activo", categoryId: "cat-sin", clubId: "c1" },
  { id: "rp16", firstName: "Adolfo", lastName: "Cruz", position: "Volante", age: 18, avatarUrl: null, verified: true, status: "activo", categoryId: "cat-sin", clubId: "c1" },
];

export const staffMembers: StaffMember[] = [
  { id: "st1", firstName: "Adolfo", lastName: "Cruz", role: "director_tecnico", age: 25, avatarUrl: null, verified: true, phone: "987182018", email: "adolfo@club.com" },
  { id: "st2", firstName: "Adolfo", lastName: "Cruz", role: "director_tecnico", age: 20, avatarUrl: null, verified: true, phone: "987654321", email: "adolfo2@club.com" },
  { id: "st3", firstName: "Adolfo", lastName: "Cruz", role: "director_tecnico", age: 18, avatarUrl: null, verified: true, phone: "912345678", email: "adolfo3@club.com" },
  { id: "st4", firstName: "Adolfo", lastName: "Cruz", role: "director_tecnico", age: 18, avatarUrl: null, verified: true, phone: "998877665", email: "adolfo4@club.com" },
  { id: "st5", firstName: "Adolfo", lastName: "Cruz", role: "delegado", age: 18, avatarUrl: null, verified: true, phone: "911223344", email: "adolfo5@club.com" },
  { id: "st6", firstName: "Adolfo", lastName: "Cruz", role: "asistente", age: 18, avatarUrl: null, verified: true, phone: "955667788", email: "adolfo6@club.com" },
];

export const teamCategories: TeamCategory[] = [
  { id: "tc-fsub15", name: "Sub 15", gender: "femenino", membersCount: 16 },
  { id: "tc-flibre", name: "Libre", gender: "femenino", membersCount: 10 },
  { id: "tc-fmaster", name: "Master", gender: "femenino", membersCount: 20 },
  { id: "tc-msub10", name: "Sub 10", gender: "masculino", membersCount: 20 },
  { id: "tc-mlibre", name: "Libre", gender: "masculino", membersCount: 30 },
  { id: "tc-mmaster", name: "Master", gender: "masculino", membersCount: 20 },
];

export const searchableDelegados: { id: string; firstName: string; lastName: string; role: string; username: string; avatarUrl: string | null }[] = [
  { id: "sd1", firstName: "Ivan Tadeo", lastName: "Flores", role: "Delegado", username: "@tadeo", avatarUrl: null },
  { id: "sd2", firstName: "Jorge", lastName: "Tadeo", role: "Delegado", username: "@Tadeo00", avatarUrl: null },
  { id: "sd3", firstName: "Jorge", lastName: "Tadeo", role: "Delegado", username: "@Mateo", avatarUrl: null },
];

export const communityPlayers: RosterPlayer[] = [
  { id: "cp1", firstName: "Emilio", lastName: "Torres", position: "Volante", age: 20, avatarUrl: null, verified: true, status: "activo", categoryId: "", clubId: "" },
  { id: "cp2", firstName: "Martin", lastName: "Cardenas", position: "Volante", age: 20, avatarUrl: null, verified: true, status: "activo", categoryId: "", clubId: "" },
  { id: "cp3", firstName: "Ignacio", lastName: "Rojas", position: "Volante", age: 20, avatarUrl: null, verified: true, status: "activo", categoryId: "", clubId: "" },
  { id: "cp4", firstName: "Samuel", lastName: "Delgado", position: "Volante", age: 20, avatarUrl: null, verified: true, status: "activo", categoryId: "", clubId: "" },
  { id: "cp5", firstName: "Tomas", lastName: "Espinoza", position: "Volante", age: 20, avatarUrl: null, verified: true, status: "activo", categoryId: "", clubId: "" },
];
